language: python

python:
- 3.7

dist: xenial

sudo: true

services:
- mysql

addons:
  apt_packages:
  - libcups2-dev

install:
- pip install --upgrade pip
- pip install flake8 coveralls tox-travis

before_script:
- flake8 edc_pharmacy_dashboard
- mysql -e 'create database edc character set utf8;'

script:
- coverage run -m tox

after_success:
- coveralls

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.7
      env: TOXENV=py37-djangotrunk
    - python: 3.8
      env: TOXENV=py38-djangotrunk
